__author__ = "qiao"

"""
Conduct the first stage retrieval by the hybrid retriever 
"""

from beir.datasets.data_loader import GenericDataLoader
import faiss
import json
from nltk import word_tokenize
import numpy as np
import os
from rank_bm25 import BM25Okapi
import sys
import tqdm
import torch
from transformers import AutoTokenizer, AutoModel


def get_bm25_corpus_index(corpus):
    corpus_path = os.path.join(f"trialgpt_retrieval/bm25_corpus_{corpus}.json")

    # If already cached, load it
    if os.path.exists(corpus_path):
        corpus_data = json.load(open(corpus_path))
        tokenized_corpus = corpus_data["tokenized_corpus"]
        corpus_nctids = corpus_data["corpus_nctids"]

    else:
        tokenized_corpus = []
        corpus_nctids = []

        with open(f"dataset/{corpus}/corpus.jsonl", "r") as f:
            for line in f.readlines():
                entry = json.loads(line)
                corpus_nctids.append(entry["_id"])

                # Weighting: 3 * title, 2 * condition, 1 * text
                tokens = word_tokenize(entry["title"].lower()) * 3
                for disease in entry["metadata"]["diseases_list"]:
                    tokens += word_tokenize(disease.lower()) * 2
                tokens += word_tokenize(entry["text"].lower())

                tokenized_corpus.append(tokens)

        corpus_data = {
            "tokenized_corpus": tokenized_corpus,
            "corpus_nctids": corpus_nctids,
        }

        with open(corpus_path, "w") as f:
            json.dump(corpus_data, f, indent=4)

    bm25 = BM25Okapi(tokenized_corpus)
    return bm25, corpus_nctids


def get_medcpt_corpus_index(corpus):
    corpus_path = f"trialgpt_retrieval/{corpus}_embeds.npy"
    nctids_path = f"trialgpt_retrieval/{corpus}_nctids.json"

    # If already cached, load it
    if os.path.exists(corpus_path):
        embeds = np.load(corpus_path)
        corpus_nctids = json.load(open(nctids_path))

    else:
        embeds = []
        corpus_nctids = []

        model = AutoModel.from_pretrained("ncbi/MedCPT-Article-Encoder").to("cuda")
        tokenizer = AutoTokenizer.from_pretrained("ncbi/MedCPT-Article-Encoder")

        with open(f"dataset/{corpus}/corpus.jsonl", "r") as f:
            print("Encoding the corpus")
            for line in tqdm.tqdm(f.readlines()):
                entry = json.loads(line)
                corpus_nctids.append(entry["_id"])

                title = entry["title"]
                text = entry["text"]

                with torch.no_grad():
                    encoded = tokenizer(
                        [[title, text]],
                        truncation=True,
                        padding=True,
                        return_tensors='pt',
                        max_length=512,
                    ).to("cuda")

                    embed = model(**encoded).last_hidden_state[:, 0, :]

                    embeds.append(embed[0].cpu().numpy())

        embeds = np.array(embeds)
        np.save(corpus_path, embeds)
        with open(nctids_path, "w") as f:
            json.dump(corpus_nctids, f, indent=4)

    index = faiss.IndexFlatIP(768)
    index.add(embeds)

    return index, corpus_nctids


if __name__ == "__main__":
    # Different corpora, e.g., "trec_2021", "trec_2022", "sigir"
    corpus = sys.argv[1]

    # Query type (e.g., "deepseek-70b")
    q_type = sys.argv[2]

    # Different k for fusion
    k = int(sys.argv[3])

    # BM25 weight
    bm25_wt = int(sys.argv[4])

    # MedCPT weight
    medcpt_wt = int(sys.argv[5])

    # Number of trials to rank
    N = 2000

    # Load qrels (ground-truth relevance judgments)
    _, _, qrels = GenericDataLoader(data_folder=f"dataset/{corpus}/").load(split="test")

    # Load the keyword file generated by keyword_generation.py
    keyword_file_path = f"/content/TrialGPT/results/retrieval_keywords_{corpus}.json"
    id2queries = json.load(open(keyword_file_path))

    # Load retrieval indices
    bm25, bm25_nctids = get_bm25_corpus_index(corpus)
    medcpt, medcpt_nctids = get_medcpt_corpus_index(corpus)

    # Load the query encoder for MedCPT
    model = AutoModel.from_pretrained("ncbi/MedCPT-Query-Encoder").to("cuda")
    tokenizer = AutoTokenizer.from_pretrained("ncbi/MedCPT-Query-Encoder")

    # Output path for retrieval results
    output_path = f"results/qid2nctids_results_{q_type}_{corpus}_k{k}_bm25wt{bm25_wt}_medcptwt{medcpt_wt}_N{N}.json"

    qid2nctids = {}
    recalls = []

    # Process each query
    with open(f"dataset/{corpus}/queries.jsonl", "r") as f:
        for line in tqdm.tqdm(f.readlines()):
            entry = json.loads(line)
            query = entry["text"]
            qid = entry["_id"]

            if qid not in qrels:
                continue

            truth_sum = sum(qrels[qid].values())

            # Retrieve keywords (conditions)
            if qid not in id2queries:
                print(f"Warning: Query ID {qid} not found in keyword file.")
                conditions = []
            else:
                conditions = id2queries[qid].get("conditions", [])
                if not conditions:
                    conditions = [id2queries[qid].get("summary", "")]  # Use summary as fallback

            # If no conditions, skip retrieval
            if len(conditions) == 0:
                nctid2score = {}
            else:
                # BM25 retrieval
                bm25_condition_top_nctids = []
                for condition in conditions:
                    tokens = word_tokenize(condition.lower())
                    top_nctids = bm25.get_top_n(tokens, bm25_nctids, n=N)
                    bm25_condition_top_nctids.append(top_nctids)

                # MedCPT retrieval
                with torch.no_grad():
                    encoded = tokenizer(
                        conditions,
                        truncation=True,
                        padding=True,
                        return_tensors='pt',
                        max_length=256,
                    ).to("cuda")

                    embeds = model(**encoded).last_hidden_state[:, 0, :].cpu().numpy()
                    scores, inds = medcpt.search(embeds, k=N)

                medcpt_condition_top_nctids = [
                    [medcpt_nctids[ind] for ind in ind_list] for ind_list in inds
                ]

                nctid2score = {}

                # Scoring
                for condition_idx, (bm25_top_nctids, medcpt_top_nctids) in enumerate(
                    zip(bm25_condition_top_nctids, medcpt_condition_top_nctids)
                ):
                    if bm25_wt > 0:
                        for rank, nctid in enumerate(bm25_top_nctids):
                            nctid2score[nctid] = nctid2score.get(nctid, 0) + (
                                1 / (rank + k)
                            ) * (1 / (condition_idx + 1))

                    if medcpt_wt > 0:
                        for rank, nctid in enumerate(medcpt_top_nctids):
                            nctid2score[nctid] = nctid2score.get(nctid, 0) + (
                                1 / (rank + k)
                            ) * (1 / (condition_idx + 1))

            qid2nctids[qid] = sorted(nctid2score, key=nctid2score.get, reverse=True)[:N]

    with open(output_path, "w") as f:
        json.dump(qid2nctids, f, indent=4)
